name: Echo on remove machine
on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Echo to vps
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: echo "Hello from Github Actions" \
                  ls -la
